export const MODAL_OPEN = "MODAL_OPEN";

export const EMPLOYEE_SELECTED = "EMPLOYEE_SELECTED";

export const EMPLOYEE_FETCH_REQUESTED = "EMPLOYEE_FETCH_REQUESTED";
export const EMPLOYEE_FETCH_SUCCEEDED = "EMPLOYEE_FETCH_SUCCEEDED";
export const EMPLOYEE_FETCH_FAILED = "EMPLOYEE_FETCH_FAILED";

export const EMPLOYEE_ADD_REQUESTED = "EMPLOYEE_ADD_REQUESTED";
export const EMPLOYEE_ADD_SUCCEEDED = "EMPLOYEE_ADD_SUCCEEDED";
export const EMPLOYEE_ADD_FAILED = "EMPLOYEE_ADD_FAILED";

export const EMPLOYEE_UPDATE_REQUESTED = "EMPLOYEE_UPDATE_REQUESTED";
export const EMPLOYEE_UPDATE_SUCCEEDED = "EMPLOYEE_UPDATE_SUCCEEDED";
export const EMPLOYEE_UPDATE_FAILED = "EMPLOYEE_UPDATE_FAILED";

export const EMPLOYEE_DELETE_REQUESTED = "EMPLOYEE_DELETE_REQUESTED";
export const EMPLOYEE_DELETE_SUCCEEDED = "EMPLOYEE_DELETE_SUCCEEDED";
export const EMPLOYEE_DELETE_FAILED = "EMPLOYEE_DELETE_FAILED";

export const USER_SELECTED = "USER_SELECTED";

export const USER_FETCH_REQUESTED = "USER_FETCH_REQUESTED";
export const USER_FETCH_SUCCEEDED = "USER_FETCH_SUCCEEDED";
export const USER_FETCH_FAILED = "USER_FETCH_FAILED";

export const USER_ADD_REQUESTED = "USER_ADD_REQUESTED";
export const USER_ADD_SUCCEEDED = "USER_ADD_SUCCEEDED";
export const USER_ADD_FAILED = "USER_ADD_FAILED";

export const USER_UPDATE_REQUESTED = "USER_UPDATE_REQUESTED";
export const USER_UPDATE_SUCCEEDED = "USER_UPDATE_SUCCEEDED";
export const USER_UPDATE_FAILED = "USER_UPDATE_FAILED";

export const USER_DELETE_REQUESTED = "USER_DELETE_REQUESTED";
export const USER_DELETE_SUCCEEDED = "USER_DELETE_SUCCEEDED";
export const USER_DELETE_FAILED = "USER_DELETE_FAILED";

export const USER_LOGIN_REQUESTED = "USER_LOGIN_REQUESTED";
export const USER_LOGIN_SUCCEEDED = "USER_LOGIN_SUCCEEDED";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_LOGOUT_REQUESTED = "USER_LOGOUT_REQUESTED";
export const USER_LOGOUT_SUCCEEDED = "USER_LOGOUT_SUCCEEDED";
export const USER_LOGOUT_FAILED = "USER_LOGOUT_FAILED";
